### ISSUE TITLE
lets me check balance, but not rain. other users not affected.

### ISSUE THREAD

**Issue by justinvforvendetta** [unek/node-tip-bot#18]
the bot suddenly started ignoring my !rain and !tip commands, but still shows me my balance when i !balance

no other users are affected; everyone else is able to rain and tip.

**Comment by justinvforvendetta** [comment]
still having the issue, and now one more user is as well. everyone else can tip/rain/balance, but now me and another can only check balance, not tip or rain.

when we tip and rain, the bot only responds when no number is entered with what the proper syntax is, but when a number is entered its ignored completely..

**Comment by dobbscoin** [comment]
But just YOU?
No one else in channel has this issue?

On Sat, Jan 3, 2015 at 5:43 PM, sunerok <notifications@github.com> wrote:

> still having the issue, and now one more user is as well. everyone else
> can tip/rain/balance, but now me and another can only check balance, not
> tip or rain.
>
> when we tip and rain, the bot only responds when no number is entered with
> what the proper syntax is, but when a number is entered its ignored
> completely..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unek/node-tip-bot/issues/18#issuecomment-68614304>.
>



-- 



BitCoin Bob  <dobbscoin@gmail.com>
DobbsCOIN (BOB): The stupider it looks ..the more important it probably is.
The ONLY cryptocurrency accepted on the Pleasure Saucers
Love that "BOB" - Get Slack w/Dobbscoin.

DONATE (BOB) or (BTC) to the same address:
1Nm828hb49kozFsNkfmWzYpMZx2SJueQPZ

**Comment by justinvforvendetta** [comment]
well, now one other user has the issue. but everyone else can rain/tip.

**Comment by dobbscoin** [comment]
can i come watch?
where are you at?

On Sat, Jan 3, 2015 at 6:22 PM, sunerok <notifications@github.com> wrote:

> well, now one other user has the issue. but everyone else can rain/tip.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unek/node-tip-bot/issues/18#issuecomment-68615344>.
>



-- 



BitCoin Bob  <dobbscoin@gmail.com>
DobbsCOIN (BOB): The stupider it looks ..the more important it probably is.
The ONLY cryptocurrency accepted on the Pleasure Saucers
Love that "BOB" - Get Slack w/Dobbscoin.

DONATE (BOB) or (BTC) to the same address:
1Nm828hb49kozFsNkfmWzYpMZx2SJueQPZ

**Comment by justinvforvendetta** [comment]
#dogecoindark on freenode

**Comment by justinvforvendetta** [comment]
im dogedDEV at the top, and coiner561 also has the issue

**Comment by justinvforvendetta** [comment]
any ideas? @unek ?

**Comment by justinvforvendetta** [comment]
still has issue

**Comment by justinvforvendetta** [comment]
ok  didnt see the previous commit by unek, bot appears to be alive and better than ever. thanks guys!
