### ISSUE TITLE
Error while trying to connect toirc.rizon.net via SSL

### ISSUE THREAD

**Issue by LordZeroHour** [unek/node-tip-bot#5]
I tried to connect with theses settings:
connection:
  host: irc.rizon.net
  port: 9999
  secure: true
  debug: true

And I got these errors:
info:    Connecting to coind...
info:    Running webadmin on port 3901
info:    Connecting to the server...
info:    Connected to JSON RPC API. Current total balance is 0Đ
23 Jun 14:24:59 - Connection got "close" event
23 Jun 14:24:59 - Disconnected: reconnecting
23 Jun 14:24:59 - Waiting 2000ms before retrying
23 Jun 14:24:59 - Unhandled message: { prefix: 'irc.rizon.io',
  server: 'irc.rizon.io',
  command: '439',
  rawCommand: '439',
  commandType: 'normal',
  args: [ '*', 'Please wait while we process your connection.' ] }
23 Jun 14:24:59 - Connection got "end" event

**Comment by unek** [comment]
blame rizon or https://github.com/martynsmith/node-irc
